name: Build and push Docker image

on:
  push:
    branches:
      - frontend-dev-sakun

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: sakunchamikara
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: sakunchamikara/stellardrive
        tags: latest
