name: Docker image

on:
  push:
    branches: [frontend-dev-sakun]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: 
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the docker image
      run: docker build . --file Dockerfile --tag stellar-image:$(date +%s)
      
    - name: Docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/stellardrive